# Generated by Django 4.0.6 on 2022-07-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, default=None, editable=False, max_length=100, verbose_name='URL slug')),
                ('description', models.TextField(max_length=4096, verbose_name='Description')),
                ('photo', models.ImageField(upload_to='photo', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
