# Generated by Django 4.0.6 on 2022-07-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_gallery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(upload_to='static/photo', verbose_name='Photo'),
        ),
    ]
